<a href="https://colab.research.google.com/github/offLaneqq/Data_Science/blob/main/2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.arange(0, 20)
a.resize(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.zeros([2,2,3]).astype(int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
np.ones([5, 2], int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
ones = np.eye(5)
diag = np.diag(ones)

In [ ]:
b = np.append([[1, 2, 3], [4, 5, 6]], [[7], [8]], axis=1)
b

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [ ]:
b > 4

array([[False, False, False,  True],
       [False,  True,  True,  True]])

In [ ]:
b[b>4]

array([7, 5, 6, 8])

In [ ]:
a = [1]*10 + list(range(10,15))
print ('a=', a)
print ('np.mean(a)=', np.mean(a))
print ('np.std(a)=', np.std(a))
print ('np.median(a)=', np.median(a))
print ('np.sum(a)=', np.sum(a))
print ('np.min(a)=', np.min(a))

a= [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10, 11, 12, 13, 14]
np.mean(a)= 4.666666666666667
np.std(a)= 5.2493385826745405
np.median(a)= 1.0
np.sum(a)= 70
np.min(a)= 1


**1. Computing Pi**

Knowing that pi is area of circle of `r = 1` which computed `S = πr2`, estimate the
 value with the help of distribution.

In [ ]:
import math as m
import numpy as np

r = 1
s = m.pi * (r ** 2)
print(s)

3.141592653589793
